@extends('layouts.main')
    @section('content')
    <section >
        <div class="container" >
        <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Cancellation and Refund Policy</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Amount paid towards purchases of courses will neither be refunded nor adjusted under any circumstance. Our customer service team would be available to address any concerns related to the product and services rendered by us. For further information, please write to us at crm@icagroup.in or reach our CRM dept. @ 1800-345-8000</span></p>
            <p>&nbsp;</p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Your Consent</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">By registering with us, you are expressly consenting to our collection, processing, storing, disclosing, and handling of your information as set forth in this Policy now and as amended by us from time to time. Processing your information in any way includes collecting, storing, deleting, using, combining, sharing, transferring, and disclosing information. We believe that every user of our Platforms must be in a position to provide informed consent prior to providing any Information required for the use of any of the Platforms. Even if you reside outside India, your information will be transferred, processed, and stored in accordance with the applicable data protection laws of India.</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br>Changes to our Privacy Policy</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">We reserve the right to update, change or modify this policy at any time. Changes to our policy will be updated on our platforms only. You are advised to review this Policy regularly for any changes, as continued use is deemed approval of all changes. This policy was last updated on January 01, 2021.</span></p>
            <p>&nbsp;</p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Authorization</span></strong><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br></span></strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">In the purview of the Telecom Regulatory Authority of India (TRAI) guidelines, you hereby authorize us and our affiliates/partners or otherwise who are accessing your Information by virtue of their association with the company to communicate with you through telephone/mobile, Email, SMS, WhatsApp or other modes of communication even if Your number/numbers(s) is/are registered in the National Do Not Call Registry (NDNC) or <a href="https://www.nccptrai.gov.in">www.nccptrai.gov.in</a></span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">You are providing your express consent to receive information, including telemarketing, about products and services from us and you hereby agree and consent to our contacting you using the information you have provided to us. We may contact you by e-mail, phone, including automated dialing equipment, SMS, WhatsApp and other kinds of text message, social networks or any other means of communication.</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br>User communications</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">When you send an email or other communication to the company, it may retain those communications in order to process your inquiries, respond to your requests and improve our Services.<br><br></span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Security Measures</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">We take utmost care to secure your Information from unauthorized access, usage or disclosure or alteration. We take appropriate steps and security measures to safeguard your Information and make sure that your Information is secured as mandated by law. For this purpose, we adopt reasonable security practices and procedures, in line with the industry standards, to include, technical, operational, managerial and physical security controls in order to protect your personal information from unauthorized access, or disclosure while it is under our control.</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">While we protect your personal information as per industry standards, you acknowledge that the internet or computer networks are not fully secure and we cannot provide any absolute assurance regarding the security of your personal information. Therefore, you shall not hold us responsible for any loss of your information, or any other data which you have shared.</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">How to Contact Us</span></strong><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br><br></span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">You may also write to us with any questions or concerns about this Privacy Policy at:</span><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br><br></span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Contact Us:</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;"><br></span><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">ICA Edu Skills Pvt. Ltd.</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Address: Unit No. ECSL1401, EcoCentre Business Park, EM Block, Sector V, Salt Lake, Kolkata, West Bengal 700091</span></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Email: crm@icagroup.in</span></strong></p>
            <p style="margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 11pt; font-family: Arial; white-space-collapse: preserve;">Phone: 8820004000</span></strong></p>
        </div>
    </section>
    @endsection
@section('script')
<!-- ============================================================== -->
<!-- CHARTS -->
@endsection